---
# make sure we have consistent codebase on repository
name: Java CI with bld
on:
  push:
    branches: [ "*" ]
  workflow_dispatch: # allows manual run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/cache@v4
        with:
          path: lib
          key: bld-${{ hashFiles('src/bld/java/**') }}
        id: cache
      - if: steps.cache.outputs.cache-hit != 'true'
        run: ./bld clean download
      - run: ./bld compile test
